# Generated by Django 3.1.3 on 2023-06-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mecanicos',
            new_name='Mecanico',
        ),
    ]
