# Generated by Django 3.1.3 on 2023-06-24 08:54

import TallerMecanico.Taller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0004_usuariolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to=TallerMecanico.Taller.models.imagen)),
            ],
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
        migrations.DeleteModel(
            name='UsuarioLog',
        ),
    ]
